# Setting the color combinations
from enum import Enum, IntEnum, auto

DARK, LIGHT = range(2)
FG_BLACK, FG_RED, FG_GREEN, FG_YELLOW, FG_BLUE, FG_MAGENTA, FG_CYAN, FG_WHITE = range(30, 37 + 1)
BG_BLACK, BG_RED, BG_GREEN, BG_YELLOW, BG_BLUE, BG_MAGENTA, BG_CYAN, BG_WHITE = range(40, 47 + 1)

LIGHT_BLACK = f"\033[{LIGHT};{FG_BLACK}m"
LIGHT_RED = f"\033[{LIGHT};{FG_RED}m"
LIGHT_GREEN = f"\033[{LIGHT};{FG_GREEN}m"
LIGHT_YELLOW = f"\033[{LIGHT};{FG_YELLOW}m"
LIGHT_BLUE = f"\033[{LIGHT};{FG_BLUE}m"
LIGHT_MAGENTA = f"\033[{LIGHT};{FG_MAGENTA}m"
LIGHT_CYAN = f"\033[{LIGHT};{FG_CYAN}m"
LIGHT_WHITE = f"\033[{LIGHT};{FG_WHITE}m"

DARK_BLACK = f"\033[{DARK};{FG_BLACK}m"
DARK_RED = f"\033[{DARK};{FG_RED}m"
DARK_GREEN = f"\033[{DARK};{FG_GREEN}m"
DARK_YELLOW = f"\033[{DARK};{FG_YELLOW}m"
DARK_BLUE = f"\033[{DARK};{FG_BLUE}m"
DARK_MAGENTA = f"\033[{DARK};{FG_MAGENTA}m"
DARK_CYAN = f"\033[{DARK};{FG_CYAN}m"
DARK_WHITE = f"\033[{DARK};{FG_WHITE}m"

BLACK = LIGHT_BLACK
RED = LIGHT_RED
GREEN = LIGHT_GREEN
YELLOW = LIGHT_YELLOW
BLUE = LIGHT_BLUE
MAGENTA = LIGHT_MAGENTA
CYAN = LIGHT_CYAN
WHITE = LIGHT_WHITE


RESET = "\033[0m"
BOLD = "\033[;1m"
REVERSE = "\033[;7m"

PLUS = "[+]"
MINUS = "[-]"
WARN = "[!]"
ERROR = "[!!]"
TILDE = "[~]"
